[general]
import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

[window]
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 14.0

[colors.primary]
background = "#1b1d1e"
foreground = "#00ff10"

[colors.cursor]
text = "CellBackground"
cursor = "#00ff10"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#1b1d1e"

[colors.selection]
text = "CellForeground"
background = "#1b1d1e"

[colors.normal]
black =   "#1b1b1b"
red =     "#df5273"
green =   "#00ff10"
yellow =  "#fec252"
blue =    "#0067ff"
magenta = "#9058ff"
cyan =    "#30e5f2"
white =   "#bbbbbb"

[colors.bright]
black =   "#1b1b1b"
red =     "#f57995"
green =   "#00ff10"
yellow =  "#fee16c"
blue =    "#0067ff"
magenta = "#ad82ff"
cyan =    "#6cf7ff"
white =   "#ffffff"
